version: "3.2"
services:
  srfi_225_test:
    build: .
    volumes:
      - dependencies-volume:/dependencies
  akku:
    image: "akkuscm/akku"
    depends_on:
      - srfi_225_test
    volumes:
      - dependencies-volume:/dependencies
  kawa:
    image: "schemers/kawa"
    depends_on:
      - srfi_225_test
    volumes:
      - dependencies-volume:/dependencies
      - type: bind
        source: .
        target: /test/srfi-225
    command: "sh /test/srfi-225/docker-kawa.sh"
  chibi:
    image: "schemers/chibi"
    depends_on:
      - srfi_225_test
    volumes:
      - dependencies-volume:/dependencies
      - type: bind
        source: .
        target: /test/srfi-225
    command: "sh /test/srfi-225/docker-chibi.sh"

volumes:
  dependencies-volume:
