version: "3.2"
services:
  srfi_225_test:
    build: .
    volumes:
      - dependencies-volume:/dependencies
  gauche:
    image: "schemers/gauche"
    depends_on:
      - srfi_225_test
    volumes:
      - dependencies-volume:/dependencies
      - type: bind
        source: .
        target: /test/srfi-225
    command: "sh /test/srfi-225/docker-gauche.sh"
  chibi:
    image: "schemers/chibi"
    depends_on:
      - srfi_225_test
    volumes:
      - dependencies-volume:/dependencies
      - type: bind
        source: .
        target: /test/srfi-225
    command: "sh /test/srfi-225/docker-chibi.sh"
  kawa:
    image: "schemers/kawa"
    depends_on:
      - srfi_225_test
    volumes:
      - dependencies-volume:/dependencies
      - target:/target
      - type: bind
        source: .
        target: /test/srfi-225
    command: "sh /test/srfi-225/docker-kawa.sh"

volumes:
  dependencies-volume:
  target:
